name: build

on:
  push:
    branches: [ "main" ]

jobs:
  job1:
    name: job
    runs-on: ubuntu-latest
    outputs:
      appName: ${{ steps.set-output.outputs.appName }}
    steps:
      - name: First step
        shell: bash
        run: |
          echo ${{ github.run_id }}
          echo "APP_NAME=TEST" >> $GITHUB_ENV
          echo "appName=TEST" >> $GITHUB_OUTPUT

  job2:
    name: job2
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Second first step
        shell: bash
        run: |
          echo ${{ github.run_id }}
          echo "${{ needs.job1.outputs.appName }}"