name: build

on:
  push:
    branches: [ "main" ]

jobs:
  job1:
    name: job
    runs-on: ubuntu-latest
    outputs:
      appName: ${{ steps.first.outputs.appName }}
    steps:
      - name: First step
        id: first
        shell: bash
        run: |
          echo ${{ github.run_id }}
          APP_NAME="TEST-task"
          echo "APP_NAME=${APP_NAME}" >> $GITHUB_ENV
          echo "appName=${APP_NAME}" >> $GITHUB_OUTPUT

      - name: Second step
        shell: bash
        run: |
          echo ${APP_NAME}

  job2:
    name: job2
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Second first step
        shell: bash
        run: |
          echo ${{ github.run_id }}
          echo "${{ env.APP_NAME }}"
          if [[ "${{ env.APP_NAME }}" == *-task ]]; then
            echo "${{ env.APP_NAME%-task }}_task"
          fi
        env:
          APP_NAME: ${{ needs.job1.outputs.appName }}